import { useState } from "react";
import type { CompileResult } from "@workspace/api-client-react";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { FileText, Search } from "lucide-react";

const TOKEN_COLORS: Record<string, string> = {
  KEYWORD:    "bg-blue-500/15 text-blue-300 border-blue-500/25",
  IDENTIFIER: "bg-emerald-500/15 text-emerald-300 border-emerald-500/25",
  NUMBER:     "bg-amber-500/15 text-amber-300 border-amber-500/25",
  STRING:     "bg-rose-500/15 text-rose-300 border-rose-500/25",
  OPERATOR:   "bg-purple-500/15 text-purple-300 border-purple-500/25",
  DELIMITER:  "bg-slate-500/15 text-slate-400 border-slate-500/25",
  BOOLEAN:    "bg-cyan-500/15 text-cyan-300 border-cyan-500/25",
  NULL:       "bg-orange-500/15 text-orange-300 border-orange-500/25",
  EOF:        "bg-muted/30 text-muted-foreground border-border",
  UNKNOWN:    "bg-red-500/15 text-red-300 border-red-500/25",
};

const TOKEN_TYPES = ["ALL", "KEYWORD", "IDENTIFIER", "NUMBER", "STRING", "OPERATOR", "DELIMITER", "BOOLEAN", "NULL"];

interface Props { result: CompileResult | null; }

export default function TokensPage({ result }: Props) {
  const [search, setSearch] = useState("");
  const [typeFilter, setTypeFilter] = useState("ALL");

  if (!result) {
    return (
      <div className="flex flex-col items-center justify-center py-20 text-center">
        <FileText className="h-10 w-10 text-muted-foreground mb-3" />
        <div className="text-sm font-medium text-foreground">No compilation result yet</div>
        <div className="text-xs text-muted-foreground mt-1">Run the pipeline from the Dashboard first</div>
      </div>
    );
  }

  const filtered = result.tokens.filter(t => {
    if (typeFilter !== "ALL" && t.type !== typeFilter) return false;
    if (search && !t.value.toLowerCase().includes(search.toLowerCase()) && !t.type.toLowerCase().includes(search.toLowerCase())) return false;
    return true;
  });

  const typeCounts = result.tokens.reduce((acc, t) => {
    acc[t.type] = (acc[t.type] ?? 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  return (
    <div className="space-y-4 max-w-[1100px]">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold tracking-tight">Token Stream</h1>
          <p className="text-sm text-muted-foreground mt-0.5">{result.tokens.length} tokens generated by the lexer</p>
        </div>
        <div className="flex items-center gap-2">
          <div className="relative">
            <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-muted-foreground" />
            <Input
              data-testid="input-token-search"
              value={search}
              onChange={e => setSearch(e.target.value)}
              placeholder="Search tokens..."
              className="pl-8 h-8 w-48 text-xs font-mono"
            />
          </div>
          <Select value={typeFilter} onValueChange={setTypeFilter}>
            <SelectTrigger className="h-8 w-36 text-xs" data-testid="select-token-type">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {TOKEN_TYPES.map(t => (
                <SelectItem key={t} value={t}>
                  {t} {typeCounts[t] ? `(${typeCounts[t]})` : ""}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      </div>

      {/* Legend */}
      <div className="flex flex-wrap gap-2">
        {Object.entries(TOKEN_COLORS).slice(0, 8).map(([type, cls]) => (
          <Badge key={type} variant="outline" className={`font-mono text-[10px] px-2 py-0.5 ${cls}`}>
            {type} {typeCounts[type] ? `×${typeCounts[type]}` : ""}
          </Badge>
        ))}
      </div>

      {/* Token table */}
      <div className="rounded border border-border overflow-hidden">
        <table className="w-full text-xs font-mono">
          <thead>
            <tr className="border-b border-border bg-muted/30">
              <th className="text-left px-3 py-2 text-muted-foreground font-medium w-12">#</th>
              <th className="text-left px-3 py-2 text-muted-foreground font-medium w-32">Type</th>
              <th className="text-left px-3 py-2 text-muted-foreground font-medium">Value</th>
              <th className="text-right px-3 py-2 text-muted-foreground font-medium w-16">Line</th>
              <th className="text-right px-3 py-2 text-muted-foreground font-medium w-16">Col</th>
            </tr>
          </thead>
          <tbody>
            {filtered.map((token, i) => (
              <tr
                key={i}
                data-testid={`row-token-${i}`}
                className={`border-b border-border/50 hover:bg-muted/20 transition-colors ${i % 2 === 0 ? "bg-transparent" : "bg-muted/5"}`}
              >
                <td className="px-3 py-1.5 text-muted-foreground">{i + 1}</td>
                <td className="px-3 py-1.5">
                  <Badge variant="outline" className={`font-mono text-[10px] px-1.5 py-0 ${TOKEN_COLORS[token.type] ?? ""}`}>
                    {token.type}
                  </Badge>
                </td>
                <td className="px-3 py-1.5 text-foreground max-w-[400px] truncate">
                  {token.value === "" ? <span className="text-muted-foreground italic">empty</span> : token.value}
                </td>
                <td className="px-3 py-1.5 text-right text-muted-foreground">{token.line}</td>
                <td className="px-3 py-1.5 text-right text-muted-foreground">{token.column}</td>
              </tr>
            ))}
          </tbody>
        </table>
        {filtered.length === 0 && (
          <div className="py-8 text-center text-sm text-muted-foreground">No tokens match your filter</div>
        )}
      </div>
      <div className="text-xs text-muted-foreground">
        Showing {filtered.length} of {result.tokens.length} tokens
      </div>
    </div>
  );
}
